### ISSUE TITLE
Unable to set voltage value of higher than 2.5V on Logical Switch

### ISSUE THREAD

**Issue by etaardvark** [UndergroundFPV/opentx-nv14-ufpv#10]
When setting up a logical switch based on a telemetry voltage (VFAS or A1 - Total Voltage or Average Cell Voltage), using the A < X or A > X switch, it seems to be impossible to set the checked value above 2.5V.

In the September firmware this was working correctly, and I could set the switch on A1 to 3.2V so it worked as a voltage warning, but now won't trigger until the voltage is overly low at 2.5V.

**Comment by qba667** [comment]
@etaardvark that is strange, please ensure that you are running latest firmware - the telemetry value should be settable in range +-30k.
