### ISSUE TITLE
Menu out of bounds data

### ISSUE THREAD

**Issue by povlhp** [UndergroundFPV/opentx-nv14-ufpv#13]
In special functions, when I set SWEup to Reset, I need to go out and back in to determine what to reset.
List of items displayed contains 4 timers, and then entries with garbage memory contents.  So wrong index / length is used here. Array out of bounds.

**Comment by qba667** [comment]
Telemetry names are ZSTRINGS, so different format. The problem is current implementation is no ready for mixing those 2 types. Best would be passing reference to flag parameter and modifying it     when needed or performing string conversation.
