### ISSUE TITLE
Changing a model results in emergency mode

### ISSUE THREAD

**Issue by Xerxekyran** [UndergroundFPV/opentx-nv14-ufpv#14]
How to reproduce:
- Firmware version: 5e49bc48c057ef7ce62e2ea50e0408d832731f37
- Have two models created
- Switch from one model to another

What happens:
- The emergency mode is (falsely) triggered

It seems that the commit a8e7e6a656f3d8b789f059e1f9bdb7c1f0581156 or 5e49bc48c057ef7ce62e2ea50e0408d832731f37 introduced this problem.

**Comment by qba667** [comment]
@Xerxekyran it must be something different - I would assume hard fault happens. Now it is correctly displayed - before it was just masked around. Attach me your models - so I can reproduce and fix it.

**Comment by Xerxekyran** [comment]
Yeah sure here are my models. Strangely there are 3 model files but I can only see 2 on the radio. Maybe this has to do with the issue?

[MODELS.zip](https://github.com/UndergroundFPV/opentx-nv14-ufpv/files/2983011/MODELS.zip)

**Comment by qba667** [comment]
@Xerxekyran Using attached models I am able to reproduce the issue. However the restart is without hard fault. I will keep you updated.

**Comment by qba667** [comment]
@Xerxekyran  I have identified place where is crashed - it is in LUA GC.
Try rename widget directory on SD card, and report to me if you can switch models than.

**Comment by Xerxekyran** [comment]
@qba667 That fixed the problem. So renaming the folder 'WIDGETS' or even just removing the widget 'BattCheck' enables model switching again.

**Comment by qba667** [comment]
@Xerxekyran thanks for verification - I believe the problem is in disposing LUA widgets. Because of that original code contained delays in main view initialization - it has been removed - problems should be identified and solved correctly. I will inform you about progress.

**Comment by qba667** [comment]
Solved in last update in Flysky branch.
