### ISSUE TITLE
No model name nor image display

### ISSUE THREAD

**Issue by lococnc** [UndergroundFPV/opentx-nv14-ufpv#5]
On initial model creation, the home screen displays the name of the model. However, if you edit the screen panels it goes away and there is no way to recover it. Also, there are no telemetry screens available.

**Comment by qba667** [comment]
Fixed 6564b675b6be907db7d4eb212f83eee6f091a2a6

**Comment by qba667** [comment]
For telemetry we have to wait until OpentTx team will implement widget configuration.

**Comment by backman8571** [comment]
When will a new load be out so we can test Model name and Image
Regards

Per Backman

Systems Management/Network Management
Professional Services

CELL : 4698558729

Email1 : per.backman@aurea.com
Email2 : per.backman@zephyrtel.com
SKYPE: backman8571@live.com
